# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: VS2017-Win2016

variables:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release

steps:

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    arguments: --configuration $(buildConfiguration) --no-build --logger \"xunit;LogFilePath=DotNet.Project.LaunchSettings.Tests.results.xml\" DotNet.Project.LaunchSettings.Tests.result.xml

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: xunit
    testResultsFiles: '**/*Tests.results.xml'
