# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: VS2017-Win2016

variables:
  solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release

steps:
# - task: NuGetToolInstaller@0

# - task: NuGetCommand@2
#   displayName: Restore Solution
#   inputs:
#     arguments: --TargetLatestRuntimePatch=true
#     restoreSolution: $(solution)
#     command: restore

# - task: DotNetCoreCLI@2
#   inputs:
#     command: restore

# - task: MSBuild@1
#   inputs:
#     solution: $(solution)
#     platform: $(buildPlatform)
#     configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    configuration: $(buildConfiguration)

- task: DotNetCoreCLI@2
  displayName: Run Tests
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    configuration: $(buildConfiguration)
    arguments: --no-build --logger trx

- task: PublishTestResults@2
  displayName: Publish Test Results
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'
